### PR TITLE
feat: masonry

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-3] 

### Description

Masonry support for tabs.

In order to make masonry work properly without flashes and re-rendering issues had to do two PRs to our dependencies.

[One](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/360) to `react-native-collapsible-tab-view` and [one](https://github.com/Shopify/flash-list/pull/892) on `@shopify/flash-list` 

The current PR points to both of my forks just to make sure that it actually solves our issue and it does! 

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

### Follow ups:

- update react native collapsible tab view [pr](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/360) to be ready to get merged
- wait for [flash-list](https://github.com/Shopify/flash-list/pull/892) pr to get merged or use the [forked repo](https://github.com/gkartalis/flash-list) as we do in this PR (maybe move it under Artsy instead of me for everyone to have access to edit?)

### Next steps: 

How do you think we should proceed with this? It's ready but we are depending on both libraries on merging the PRs.

⚠️ FYI: I have two branches in my flash list fork. One is for [the actual PR ](https://github.com/Shopify/flash-list/pull/892)itself and the other branch (the one that I have on this package.json for flashlist) is the one that also includes the `dist` folder of the library since it throws errors because dist was in gitignore.

Not sure how to unblock this to publish a canary 🤔 Ci fails with error:
`info There appears to be trouble with your network connection. Retrying...`

But people in [stackoverflow](https://stackoverflow.com/a/51508426/7785085) say that this might happen for either no network connection on ci or even having a huge package (first thing that comes to mind is that this is due to me including the dist folder)

Happy to hear your thoughts.

#### How to run - test

- Link palette locally with `yarn local-palette-dev` on this branch `gkartalis/masonry` 
- Download eigen in this branch `gkartalis/masonry` and also run `yarn local-palette-dev`

#### Demo from eigen

It is missing the filter sticky header but can be really easily added 🔥

https://github.com/artsy/palette-mobile/assets/21178754/df9ce261-1dab-4565-ac78-b9ffc0ade2ad

[PHIRE-3]: https://artsyproduct.atlassian.net/browse/PHIRE-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

<details>
  <summary>📦 Published PR as canary version: <code>13.0.0--canary.138.614.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @artsy/palette-mobile@13.0.0--canary.138.614.0
  # or 
  yarn add @artsy/palette-mobile@13.0.0--canary.138.614.0
  ```
</details>

### CODE REVIEW

**Comment by damassi** [comment]
That network connection issue is often an ephemeral thing... give it a sec!

**Review by damassi — APPROVED** [review]
Amazing 👌

**Comment by gkartalis** [comment]
PR Got merged, making sure that everything works after I publish the canary. In theory we might not need the flashlist pr to get merged (tested it out without the flashlist patch on the collapsible tab view lib and was working great!)

**Comment by gkartalis** [comment]
Published canary version: 12.0.2--canary.138.576.0

**Review by joeyAghion — APPROVED** [review]

**Comment by artsyit** [comment]
:rocket: PR was released in [`v13.0.0`](https://github.com/artsy/palette-mobile/releases/tag/v13.0.0) :rocket:

**Pull request merged**
